version: '3'
services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"

  backend:
    build: ./backend
    ports:
      - "8080:8080"

  ml:
    build: ./ml
    ports:
      - "8000:8000"
    environment:
      - OPENAI_API_KEY=sk-proj-5Ry9FbEBcv4mmp6LYoczT3BlbkFJ3mAsn5Gi2a3nbub2Qskl